"""Write and update agentforge.yaml with comment preservation (ruamel.yaml)."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq

from agentforge.models.config import AgentForgeConfig, SourceConfig

_yaml = YAML()
_yaml.preserve_quotes = True
_yaml.default_flow_style = False
_yaml.width = 120


# ── Helpers ───────────────────────────────────────────────────────────────────


def _now_iso() -> str:
    return datetime.now(tz=UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _cm(**kwargs: Any) -> CommentedMap:
    """Build a CommentedMap from keyword arguments, preserving insertion order."""
    m = CommentedMap()
    for k, v in kwargs.items():
        m[k] = v
    return m


def _config_to_commented_map(config: AgentForgeConfig) -> CommentedMap:
    """Serialize AgentForgeConfig → CommentedMap suitable for ruamel.yaml dump."""
    root = CommentedMap()

    # meta
    root["meta"] = _cm(
        agentforge_version=config.meta.agentforge_version,
        created_at=config.meta.created_at.strftime("%Y-%m-%dT%H:%M:%SZ")
        if config.meta.created_at
        else _now_iso(),
        updated_at=_now_iso(),
    )

    # agent
    root["agent"] = _cm(
        name=config.agent.name,
        description=config.agent.description,
        version=config.agent.version,
    )

    # sources
    sources_seq = CommentedSeq()
    for src in config.sources:
        entry = _cm(id=src.id, type=src.type)
        if src.transport:
            entry["transport"] = src.transport
        if src.command:
            entry["command"] = src.command
        if src.url:
            entry["url"] = src.url
        if src.auth:
            entry["auth"] = _cm(type=src.auth.type, token_env=src.auth.token_env)
        if src.env:
            env_map = CommentedMap()
            for k, v in src.env.items():
                env_map[k] = v
            entry["env"] = env_map
        sources_seq.append(entry)
    root["sources"] = sources_seq

    # tools
    tools_map = CommentedMap()

    if config.tools.filters:
        filters_map = CommentedMap()
        for src_id, flt in config.tools.filters.items():
            flt_entry = CommentedMap()
            if flt.include is not None:
                seq = CommentedSeq(flt.include)
                flt_entry["include"] = seq
            if flt.exclude is not None:
                seq = CommentedSeq(flt.exclude)
                flt_entry["exclude"] = seq
            filters_map[src_id] = flt_entry
        tools_map["filters"] = filters_map

    if config.tools.rename:
        rename_map = CommentedMap()
        for k, v in config.tools.rename.items():
            rename_map[k] = v
        tools_map["rename"] = rename_map

    if config.tools.descriptions:
        desc_map = CommentedMap()
        for k, v in config.tools.descriptions.items():
            desc_map[k] = v
        tools_map["descriptions"] = desc_map

    root["tools"] = tools_map

    # quality
    root["quality"] = _cm(
        warn_below=config.quality.warn_below,
        block_below=config.quality.block_below,
    )

    # generate
    root["generate"] = _cm(
        output_dir=config.generate.output_dir,
        emit=_cm(
            agent_card=config.generate.emit.agent_card,
            tool_manifest=config.generate.emit.tool_manifest,
            system_prompt=config.generate.emit.system_prompt,
        ),
    )

    return root


# ── Public API ────────────────────────────────────────────────────────────────


def write_new(config: AgentForgeConfig, path: Path | str) -> None:
    """Write a brand-new agentforge.yaml from an AgentForgeConfig.

    Creates parent directories if needed. Overwrites any existing file.

    Args:
        config: The config to serialise.
        path: Destination file path (typically ``./agentforge.yaml``).
    """
    dest = Path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)

    root = _config_to_commented_map(config)

    # Top-of-file comment
    root.yaml_set_start_comment(
        "agentforge.yaml — generated by agentforge\n"
        "Edit this file to curate, rename, and enrich your agent's tools.\n"
    )

    with dest.open("w", encoding="utf-8") as fh:
        _yaml.dump(root, fh)


def add_source(source: SourceConfig, path: Path | str) -> None:
    """Append a new source entry to an existing agentforge.yaml.

    Preserves all existing content and comments. Raises ``ValueError`` if a
    source with the same ``id`` already exists.

    Args:
        source: The new source to add.
        path: Path to the existing agentforge.yaml.
    """
    dest = Path(path)

    with dest.open("r", encoding="utf-8") as fh:
        data = _yaml.load(fh)

    if data is None or not isinstance(data, dict):
        raise ValueError(f"{dest} does not contain a valid YAML mapping.")

    sources = data.get("sources")
    if sources is None:
        data["sources"] = CommentedSeq()
        sources = data["sources"]

    # Duplicate check
    for existing in sources:
        if isinstance(existing, dict) and existing.get("id") == source.id:
            raise ValueError(
                f"Source '{source.id}' already exists in {dest}. "
                "Use a different id or edit the file manually."
            )

    entry = _cm(id=source.id, type=source.type)
    if source.transport:
        entry["transport"] = source.transport
    if source.command:
        entry["command"] = source.command
    if source.url:
        entry["url"] = source.url
    if source.auth:
        entry["auth"] = _cm(type=source.auth.type, token_env=source.auth.token_env)
    if source.env:
        env_map = CommentedMap()
        for k, v in source.env.items():
            env_map[k] = v
        entry["env"] = env_map

    sources.append(entry)

    # Update meta.updated_at if present
    if isinstance(data.get("meta"), dict):
        data["meta"]["updated_at"] = _now_iso()

    with dest.open("w", encoding="utf-8") as fh:
        _yaml.dump(data, fh)


def update_descriptions(descriptions: dict[str, str], path: Path | str) -> None:
    """Merge description overrides into ``tools.descriptions`` in an existing file.

    Existing keys are overwritten; other keys are untouched. New keys are
    appended. Comments in the rest of the file are preserved.

    Args:
        descriptions: Mapping of tool name → curated description string.
        path: Path to the existing agentforge.yaml.
    """
    dest = Path(path)

    with dest.open("r", encoding="utf-8") as fh:
        data = _yaml.load(fh)

    if data is None or not isinstance(data, dict):
        raise ValueError(f"{dest} does not contain a valid YAML mapping.")

    tools = data.setdefault("tools", CommentedMap())
    desc_map = tools.setdefault("descriptions", CommentedMap())

    for tool_name, description in descriptions.items():
        desc_map[tool_name] = description

    if isinstance(data.get("meta"), dict):
        data["meta"]["updated_at"] = _now_iso()

    with dest.open("w", encoding="utf-8") as fh:
        _yaml.dump(data, fh)
